DATASET:
    NAME: "ade20k"
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
    MODE: 'val'
TRAIN:
    EPOCHS: 120
    BATCH_SIZE: 16
    CROP_SIZE: 480
    BASE_SIZE: 520
    BACKBONE_PRETRAINED_KEY: "model"
TEST:
    BATCH_SIZE: 16

SOLVER:
    LR: 6e-5
    DECODER_LR_FACTOR: 1.0
    WEIGHT_DECAY: 1e-2
    WARMUP:
        EPOCHS: 2.37
        FACTOR: 1e-6
    OPTIMIZER: "adamw"
    AUX: True

MODEL:
    MODEL_NAME: "MaskFormer"
    BACKBONE: "swin_b_224"
    BN_TYPE: "LN"
    MASKFORMER:
        IN_CHANNELS: [128, 256, 512, 1024]
