DATASET:
    NAME: "ade20k"
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
    MODE: 'val'
TRAIN:
    EPOCHS: 120
    BATCH_SIZE: 8
    CROP_SIZE: 480
    BASE_SIZE: 520
    BACKBONE_PRETRAINED_KEY: "model"
TEST:
    BATCH_SIZE: 8

SOLVER:
    LOSS_NAME: "dice"
    OPTIMIZER: "adamw"
    LR: 0.002

MODEL:
    MODEL_NAME: "UPerNet"
    BACKBONE: "swin_t_224"
    BN_TYPE: "LN"
    BN_EPS_FOR_ENCODER: 1e-3
    UPERNET:
        IN_CHANNELS: [96, 192, 384, 768]
