DATASET:
    NAME: "cityscape"
    MEAN: [.485, .456, .406]
    STD: [.229, .224, .225]
TRAIN:
    EPOCHS: 100
    BATCH_SIZE: 4
    CROP_SIZE: 713
    BACKBONE_PRETRAINED_KEY: 'model'
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (1025, 2049)

SOLVER:
    LR: 0.001
    OPTIMIZER: "adamw"
    AUX: True
    AUX_WEIGHT: 0.4

AUG:
    BLUR_PROB: 0.5

MODEL:
    MODEL_NAME: "UPerNet"
    BACKBONE: "swin_b_224"
    BN_TYPE: "LN"
    UPERNET.IN_CHANNELS: [128, 256, 512, 1024]
