DATASET:
    NAME: "cityscape"
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
TRAIN:
    EPOCHS: 200
    BATCH_SIZE: 2
    CROP_SIZE: 769
TEST:
    BATCH_SIZE: 2
    CROP_SIZE: (1025, 2049)
#    TEST_MODEL_PATH: trained_models/deeplabv3_plus_xception_segmentron.pth

SOLVER:
    LR: 0.02

MODEL:
    MODEL_NAME: "PointRend"
    BACKBONE: "xception65"
    BN_EPS_FOR_ENCODER: 1e-3
    DEEPLABV3_PLUS:
        ENABLE_DECODER: False
