DATASET:
    NAME: "pascal_voc"
    MEAN: [.485, .456, .406]
    STD: [.229, .224, .225]
    MODE: 'val'
TRAIN:
    EPOCHS: 50
    BATCH_SIZE: 4
    CROP_SIZE: 480
    BASE_SIZE: 520
    BACKBONE_PRETRAINED_KEY: 'model'

TEST:
    BATCH_SIZE: 4

SOLVER:
    LR: 0.0001
    OPTIMIZER: "adamw"

MODEL:
    MODEL_NAME: "UPerNet"
    BACKBONE: "swin_t_224"
    BN_TYPE: "LN"
    BN_EPS_FOR_ENCODER: 1e-3
    UPERNET.IN_CHANNELS: [96, 192, 384, 768]