DATASET:
    NAME: "pascal_voc"
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
    MODE: 'val'
TRAIN:
    EPOCHS: 50
    BATCH_SIZE: 8
    CROP_SIZE: 224
    BASE_SIZE: 520

TEST:
    BATCH_SIZE: 8

SOLVER:
    LR: 0.0001

MODEL:
    MODEL_NAME: "UPerNet"
    UPERNET.IN_CHANNELS: [256, 512, 1024, 2048]
    BACKBONE: "resnet101"
    BN_EPS_FOR_ENCODER: 1e-3