DATASET:
    NAME: "pascal_voc"
    MEAN: [.485, .456, .406]
    STD: [.229, .224, .225]
    MODE: 'val'
TRAIN:
    EPOCHS: 50
    BATCH_SIZE: 8
    CROP_SIZE: 480
    BASE_SIZE: 520
    BACKBONE_PRETRAINED_KEY: 'model'

TEST:
    BATCH_SIZE: 8

SOLVER:
    LR: 6e-5
    DECODER_LR_FACTOR: 1.0
    WEIGHT_DECAY: 1e-2
    WARMUP:
        EPOCHS: 2.37
        FACTOR: 1e-6
    OPTIMIZER: "adamw"
    AUX: True

MODEL:
    MODEL_NAME: "MaskFormer"
    BACKBONE: "swin_t_224"
    BN_TYPE: "LN"
    MASKFORMER:
        IN_CHANNELS: [96, 192, 384, 768]